### ISSUE TITLE
Fix: Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

### ISSUE THREAD

**Issue by gahooa** [appcove/developer-software#2]
**We are using an outdated key management technique**

------

The accepted answer here has the solution.
https://stackoverflow.com/questions/68992799/warning-apt-key-is-deprecated-manage-keyring-files-in-trusted-gpg-d-instead

First instruction should be to get the key:
`curl -s https://appcove.github.io/developer-software/ubuntu/KEY.gpg | sudo dd of=/usr/share/keyrings/appcove-developer-software.gpg`

`curl -s "https://appcove.github.io/developer-software/ubuntu/appcove-developer-software.list" | sudo dd of=/etc/apt/sources.list.d/appcove-developer-software.list`

`sudo apt update`

`sudo apt install git-excess pastel`

------

To reproduce:

`docker run --rm -it ubuntu:22.04`
`apt update`
`apt install curl gnupg vim`

Then follow the directions in the repo to get the warning...

**Comment by DilecPadovani** [comment]
Done in 88d25f95954a61f2557dd185a500bee283503942

**Comment by gahooa** [comment]
`tee` vs `dd` ?

Seems like tee having to write out to /dev/null is extra characters that are not needed

**Comment by DilecPadovani** [comment]
Replaced /dev/null by using `gpg` flag `-o`
