### ISSUE TITLE
Repo path should have ubuntu release as part of it

### ISSUE THREAD

**Issue by gahooa** [appcove/developer-software#3]
Right now the repo is at `https://appcove.github.io/developer-software/ubuntu`, which is find as a BASE url

We are missing the concept of jammy/main...

Here is an example from an official ubunto repo:
deb http://archive.ubuntu.com/ubuntu/ jammy main

Read up on this:
https://wiki.debian.org/DebianRepository/Format#Overview

And the .list file should be:

`deb [signed-by=...] https://appcove.github.io/developer-software/ubuntu jammy main`

Also - where does the architecture play in?  If we have ubuntu installed on a different (not amd64) system, what will happen?

**Comment by DilecPadovani** [comment]
@gahooa What architecture should we be targeting?

**Comment by DilecPadovani** [comment]
Usefull link: https://www.debian.org/doc/manuals/maint-guide/advanced.en.html

**Comment by gahooa** [comment]
@DilecPadovani the only architecture we need to target now is amd64

**Comment by gahooa** [comment]
Hi @DilecPadovani  I see on the `website` branch you added `jammy` but didn't add `main`.  

`deb [signed-by=...] https://appcove.github.io/developer-software/ubuntu jammy main`

translates into

`http://appcove.github.io/developer-software/ubuntu/jammy/main`

Take a look at the `website2` branch.

**Comment by DilecPadovani** [comment]
Last ok commit: b6c5d2e60f53f8bca5f3212dae7c9598cf5a9c60

**Comment by DilecPadovani** [comment]
@gahooa jammy/main structure working ok. When we need to expand compatibility to another arch we only have to add folder `binary-<arch>` to jammy/main.
