### ISSUE TITLE
Fix maintainer field issue

### ISSUE THREAD

**Issue by gahooa** [appcove/developer-software#4]
### The error
`dpkg: warning: parsing file '/var/lib/dpkg/status' near line 3787 package 'pastel': missing 'Maintainer' field`

### How to reproduce
```
docker run --rm -it ubuntu:22.04
apt update && apt install -y curl gpg vim sudo
curl -s https://appcove.github.io/developer-software/ubuntu/KEY.gpg | gpg --dearmor | sudo dd of=/usr/share/keyrings/appcove-developer-software.gpg
echo 'deb [signed-by=/usr/share/keyrings/appcove-developer-software.gpg] https://appcove.github.io/developer-software/ubuntu ./' | sudo dd of=/etc/apt/sources.list.d/appcove-developer-software.list
apt update
apt install pastel
```

**Comment by DilecPadovani** [comment]
The mainteiner should be the original one, me or for example dev-software@appcove.com

**Comment by gahooa** [comment]
@DilecPadovani please research this to find proper answer.  I think it should be developer-software@appcove.com

**Comment by DilecPadovani** [comment]
Done in e4b32751d1d3cd2db0bf6f4aa93c1862175b03d2
